=== Matlab-App-Toolboxes/mpa-jutil/src/main/resources/orm-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://mpa.io/orm/schema" xmlns:orm="http://mpa.io/orm/schema"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	attributeFormDefault="unqualified" version="0.1">

	<xsd:element name="entity-mappings">
		<xsd:complexType>
			<xsd:annotation>
				<xsd:documentation>
					The entity-mappings element is the root element
					of a mapping
				</xsd:documentation>
			</xsd:annotation>
			<xsd:sequence>
				<xsd:element name="description" type="xsd:string"
					minOccurs="0" />
				<xsd:element name="entity" type="orm:entity" minOccurs="0"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="entity">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="data-mapper" type="orm:data-mapper"
				minOccurs="0" maxOccurs="unbounded" />

			<xsd:element name="struct-converter" type="orm:struct-converter"
				minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="pre-persist" type="orm:pre-persist"
				minOccurs="0" />
			<xsd:element name="post-persist" type="orm:post-persist"
				minOccurs="0" />
			<xsd:element name="pre-remove" type="orm:pre-remove"
				minOccurs="0" />
			<xsd:element name="post-remove" type="orm:post-remove"
				minOccurs="0" />
			<xsd:element name="pre-update" type="orm:pre-update"
				minOccurs="0" />
			<xsd:element name="post-update" type="orm:post-update"
				minOccurs="0" />
			<xsd:element name="post-load" type="orm:post-load"
				minOccurs="0" />
			<xsd:element name="attributes" type="orm:attributes"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="class" type="xsd:string" use="required" />
		<xsd:attribute name="parent-class" type="xsd:string" />
		<xsd:attribute name="cacheable" type="xsd:boolean" />
		<xsd:attribute name="metadata-complete" type="xsd:boolean" />
		<xsd:attribute name="read-only" type="xsd:boolean" />
	</xsd:complexType>


	<xsd:complexType name="attributes">
		<xsd:annotation>
			<xsd:documentation>
				This element contains the entity field or property
				mappings.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="id" type="orm:basic" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="basic" type="orm:basic" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="basic-collection" type="orm:basic-collection"
				minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="element-collection" type="orm:element-collection"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="element-collection">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="map-key" type="xsd:string" minOccurs="0" />
			<xsd:element name="column" type="xsd:string" minOccurs="0" />
			<xsd:choice minOccurs="0" maxOccurs="2">
				<xsd:element name="converter" type="orm:converter" />
				<xsd:element name="struct-converter" type="orm:struct-converter" />
			</xsd:choice>
			<xsd:choice>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="attribute-type" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="basic-collection">
		<xsd:annotation>
			<xsd:documentation>

			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="convert" type="xsd:string" minOccurs="0" />
			<xsd:choice minOccurs="0">
				<xsd:element name="converter" type="orm:converter" />
				<xsd:element name="struct-converter" type="orm:struct-converter" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:complexType>


	<xsd:complexType name="basic">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="field" type="xsd:string" minOccurs="0" />
			<xsd:choice minOccurs="0">
				<xsd:element name="converter" type="orm:converter" />
				<xsd:element name="struct-converter" type="orm:struct-converter" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="optional" type="xsd:boolean" />
		<xsd:attribute name="attribute-type" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="data-mapper">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="class" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="converter">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="class" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="struct-converter">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="converter" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="pre-persist">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="method-name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="post-persist">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="method-name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="pre-remove">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="method-name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="pre-update">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="method-name" type="xsd:string" use="required" />
	</xsd:complexType>
	<xsd:complexType name="post-remove">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="method-name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="post-update">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="method-name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="post-load">
		<xsd:annotation>
			<xsd:documentation>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="method-name" type="xsd:string" use="required" />
	</xsd:complexType>

</xsd:schema>

=== Matlab-App-Toolboxes/mpa-jutil/src/test/resources/calibration-orm.xml
<entity-mappings xmlns="http://mpa.io/orm/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mpa.io/orm/schema orm-schema.xsd ">
	<description></description>
	<entity class="entity.Basic" name="basic">
		<attributes>
			<id name="id" attribute-type="string">
				<field>mpa.types.DataTimeId</field>
			</id>
			<basic name="string" attribute-type="string" />
			<basic name="double" attribute-type="double" />
			<basic name="int" attribute-type="int" />
		</attributes>
	</entity>

	<entity class="entity.Collections" name="collections">
		<attributes>
			<id name="id" attribute-type="string">
				<field>mpa.types.DataTimeId</field>
			</id>
			<element-collection name="strings" attribute-type="string" />
			<element-collection name="doubles" attribute-type="double" />
			<element-collection name="ints" attribute-type="int" />
		</attributes>
	</entity>

	<entity class="entity.IntensityMeasurement" name="IntensityMeasurement">
		<data-manager class='TestDataManager' name='TestDataManager' />
		<attributes>
			<id name="id" attribute-type="string">
				<field>mpa.types.DataTimeId</field>
			</id>
			<basic name="calibrationDate" attribute-type="string" />
			<basic name="wavelength" attribute-type="double" />
			<basic name="wavelengthExponent" attribute-type="int" />
			<basic name="responsivity" attribute-type="double" />
			<basic name="diameterX" attribute-type="double" />
			<basic name="diameterY" attribute-type="double" />
			<basic name="diameterExponent" attribute-type="int" />
			<basic name="spotFocus" attribute-type="double" />
			<basic name="spotFocusExponent" attribute-type="int" />

			<element-collection name="voltages"
				attribute-type="double" />
			<element-collection name="voltageExponent"
				attribute-type="double" />
			<element-collection name="powers" attribute-type="double" />
			<element-collection name="powerExponent"
				attribute-type="double" />
		</attributes>
	</entity>
</entity-mappings>
